[package]
name = "culine"
version = "0.1.0"
authors = ["Jrester <jrester379@gmail.com>", "DeeJayBro <info@deejaybro.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]